[package]
name = "cjames-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
yew-router = "0.14"
wasm-bindgen-futures = "0"
lazy_static = "1"

[dependencies.wasm-bindgen]
version = "0"
features = [ "serde-serialize" ]

[dependencies.web-sys]
version = "0"
features = [ "ScrollToOptions", "ScrollBehavior", "Window", "Request" ]