[package]
name = "cjames-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.21.0"
yew-router = "0.18.0"
wasm-bindgen-futures = "0"
lazy_static = "1"