[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "css/",
    "static/",
]

[clean]
dist = "dist"
