[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "assets/",
]

[clean]
dist = "dist"

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./assets/tailwind.css -o ./dist/.stage/index.css"]