[build]
target = "index.html"
dist = "dist"
public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "assets/",
]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "tailwind"
command_arguments = ["-i", "./assets/tailwind.css", "-o", "./dist/.stage/index.css", "--minify"]