[build]
target = "index.html"
dist = "dist"
public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "assets/",
]

[clean]
dist = "dist"

[hooks]
pre_build = [
    "npx tailwindcss -i ./assets/tailwind.css -o ./assets/min-tailwind.css --minify"
]